# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(836, 615)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.sync_sentences_button = QtWidgets.QPushButton(Dialog)
        self.sync_sentences_button.setObjectName("sync_sentences_button")
        self.gridLayout_1.addWidget(self.sync_sentences_button, 6, 1, 1, 1)
        self.sentences_list = QtWidgets.QListWidget(Dialog)
        self.sentences_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sentences_list.setObjectName("sentences_list")
        self.gridLayout_1.addWidget(self.sentences_list, 5, 1, 1, 1)
        self.sentences_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sentences_label.setFont(font)
        self.sentences_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sentences_label.setObjectName("sentences_label")
        self.gridLayout_1.addWidget(self.sentences_label, 2, 1, 1, 1)
        self.langComboBox = QtWidgets.QComboBox(Dialog)
        self.langComboBox.setObjectName("langComboBox")
        self.gridLayout_1.addWidget(self.langComboBox, 0, 1, 1, 1)
        self.textBox = QtWidgets.QPlainTextEdit(Dialog)
        self.textBox.setObjectName("textBox")
        self.gridLayout_1.addWidget(self.textBox, 10, 0, 1, 2)
        self.add_word_button = QtWidgets.QPushButton(Dialog)
        self.add_word_button.setObjectName("add_word_button")
        self.gridLayout_1.addWidget(self.add_word_button, 6, 0, 1, 1)
        self.import_words_button = QtWidgets.QPushButton(Dialog)
        self.import_words_button.setObjectName("import_words_button")
        self.gridLayout_1.addWidget(self.import_words_button, 7, 0, 1, 1)
        self.words_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.words_label.setFont(font)
        self.words_label.setAlignment(QtCore.Qt.AlignCenter)
        self.words_label.setObjectName("words_label")
        self.gridLayout_1.addWidget(self.words_label, 2, 0, 1, 1)
        self.words_list = QtWidgets.QListWidget(Dialog)
        self.words_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.words_list.setObjectName("words_list")
        self.gridLayout_1.addWidget(self.words_list, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_1.addWidget(self.label, 0, 0, 1, 1)
        self.import_sentences_button = QtWidgets.QPushButton(Dialog)
        self.import_sentences_button.setObjectName("import_sentences_button")
        self.gridLayout_1.addWidget(self.import_sentences_button, 12, 1, 1, 1)
        self.import_text_button = QtWidgets.QPushButton(Dialog)
        self.import_text_button.setObjectName("import_text_button")
        self.gridLayout_1.addWidget(self.import_text_button, 12, 0, 1, 1)
        self.open_files_button = QtWidgets.QPushButton(Dialog)
        self.open_files_button.setObjectName("open_files_button")
        self.gridLayout_1.addWidget(self.open_files_button, 11, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "InContext"))
        self.sync_sentences_button.setToolTip(_translate("Dialog", "Fetch sentences for selected words from online providers, overriding any sentences added manually"))
        self.sync_sentences_button.setText(_translate("Dialog", "Sync from online providers"))
        self.sentences_label.setText(_translate("Dialog", "Sentences"))
        self.add_word_button.setText(_translate("Dialog", "Add word..."))
        self.import_words_button.setToolTip(_translate("Dialog", "Import from a list of words separated by blanks"))
        self.import_words_button.setText(_translate("Dialog", "Import words..."))
        self.words_label.setText(_translate("Dialog", "Words"))
        self.words_list.setSortingEnabled(True)
        self.label.setText(_translate("Dialog", "Language"))
        self.import_sentences_button.setToolTip(_translate("Dialog", "Import from a file of sentences separated by newlines"))
        self.import_sentences_button.setText(_translate("Dialog", "Import sentences for selected word"))
        self.import_text_button.setToolTip(_translate("Dialog", "Import sentences from a text file, adding sentences to the entry of each word in the text"))
        self.import_text_button.setText(_translate("Dialog", "Parse text and import sentences for found words"))
        self.open_files_button.setText(_translate("Dialog", "Open files..."))
